name: Slash Command Dispatch

on:
    issue_comment:
        types: [ created ]

jobs:
    slash-command-dispatch:
        runs-on: ubuntu-latest
        steps:
            -   name: Get GitHub App Token
                id: github-token
                uses: actions/create-github-app-token@v1
                with:
                    app_id: 960836
                    private_key: ${{ secrets.kyBOT-PRIVATE_KEY }}

            -   name: Slash Command Dispatch
                uses: peter-evans/slash-command-dispatch@13bc09769d122a64f75aa5037256f6f2d78be8c4 # v4.0.0
                with:
                    token: ${{ steps.github-token.outputs.token }}
                    commands: |
                        release