name: Publish Package

on:
    repository_dispatch:
        types: [ release-command ]
    workflow_dispatch:
        inputs:
            verUpType:
                description: "Version-Up Type"
                required: true
                type: choice
                options:
                    - "patch"
                    - "minor"
                    - "major"

env:
    kyBOT-APP_ID: 960836

jobs:
    validation:
        runs-on: ubuntu-latest
        if: ${{ !contains(fromJSON('["patch", "minor", "major"]'), (github.event.client_payload.slash_command.args.unnamed.arg1 || github.event.inputs.verUpType)) }}
        steps:

            -   name: get github app token
                id: github-token
                uses: actions/create-github-app-token@v1
                with:
                    app-id: ${{ env.kyBOT-APP_ID }}
                    private-key: ${{ secrets.kyBOT_PRIVATE_KEY }}

            -   name: Failed Report
                if: ${{ github.event.inputs.verUpType == '' }}
                uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
                with:
                    token: ${{ steps.github-token.outputs.token }}
                    repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
                    issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
                    body: |
                        The /release command requires one of major, minor, or patch.
                        
                        ```
                        /release major
                        /release minor
                        /release patch
                        ```

            -   name: Exit 2
                run: exit 2

    publish:
        runs-on: ubuntu-latest
        if: ${{ ! failure() }}
        needs:
            validation
        permissions:
            id-token: write
        steps:
            -   uses: actions/checkout@v4

            -   uses: actions/setup-node@v4
                with:
                    node-version: '22.x'
                    registry-url: 'https://registry.npmjs.org'

            -   name: Get GitHub App Token
                id: github-token
                uses: actions/create-github-app-token@v1
                with:
                    app-id: ${{ env.kyBOT-APP_ID }}
                    private-key: ${{ secrets.kyBOT_PRIVATE_KEY }}

            -   name: Cache Dependencies
                id: yarn_cache
                uses: actions/cache@v4
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            -   name: Install Dependencies
                if: steps.yarn_cache.outputs.cache-hit != 'true'
                run: yarn install

            -   name: Get Version-Up Type
                id: ver_up_type
                run: |
                    ver_up_type=${{ github.event.client_payload.slash_command.args.unnamed.arg1 || github.event.inputs.veruptype }}
                    echo "ver_up_type=$ver_up_type" >> $GITHUB_OUTPUT

            -   name: Publish Package to npmjs
                id: publish
                run: |
                    git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                    git config --local user.name "github-actions[bot]"
                    npm version `npm view @ky-y./utils version` --allow-same-version
                    version=`npm version ${{ steps.ver_up_type.outputs.VER_UP_TYPE }}`
                    npm publish --provenance
                    echo "version=$version" >> $GITHUB_OUTPUT
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            -   name: Success Report
                uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
                with:
                    token: ${{ steps.github-token.outputs.token }}
                    repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
                    issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
                    body: |
                        The release of ${{ steps.publish.outputs.version }} was completed successfully.

    failed:
        runs-on: ubuntu-latest
        if: ${{ always() && contains(needs.*.result, 'failure') }}
        needs:
            publish
        steps:
            -   name: Get GitHub App Token
                id: github-token
                uses: actions/create-github-app-token@v1
                with:
                    app-id: ${{ env.kyBOT-APP_ID }}
                    private-key: ${{ secrets.kyBOT_PRIVATE_KEY }}

            -   name: Get Action URL
                id: action-url
                run: |
                    action_url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
                    echo "action-url=$action_url" >> $GITHUB_OUTPUT

            -   name: Failed Report
                uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
                with:
                    token: ${{ steps.github-token.outputs.token }}
                    repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
                    issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
                    body: |
                        The release failed. Please check the logs.
                        
                        ${{ steps.action-url.outputs.action-url }}
