name: Test (Eslint, Vitest, Build)

on:
    push:
        branches: [ '*' ]
    pull_request:
        branches: [ '*' ]

    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - uses: oven-sh/setup-bun@v2

            - name: Cache Dependencies
              id: bun_cache
              uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}

            - name: Install Dependencies
              if: steps.bun_cache.outputs.cache-hit != 'true'
              run: bun install --frozen-lockfile


    eslint:
        runs-on: ubuntu-latest
        needs:
            - setup
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - uses: oven-sh/setup-bun@v2

            - name: Restore Cache Dependencies
              uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}

            - name: Eslint Check
              run: bun run lint


    vitest:
        runs-on: ubuntu-latest
        needs:
            - setup
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - uses: oven-sh/setup-bun@v2

            - name: Restore Cache Dependencies
              uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}

            - name: Vitest Check
              run: bun run test


    build:
        runs-on: ubuntu-latest
        needs:
            - setup
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - uses: oven-sh/setup-bun@v2

            - name: Restore Cache Dependencies
              uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}

            - name: Build Check
              run: bun run build