name: Test (Eslint, Vitest, Build)

on:
    push:
        branches: [ '*' ]
    pull_request:
        branches: [ '*' ]

    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: '22'

            - name: Cache Dependencies
              id: yarn_cache
              uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install Dependencies
              if: steps.yarn_cache.outputs.cache-hit != 'true'
              run: yarn install


    eslint:
        runs-on: ubuntu-latest
        needs:
            - setup
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: '22'

            - name: Restore Cache Dependencies
              uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Eslint Check
              run: yarn eslint


    vitest:
        runs-on: ubuntu-latest
        needs:
            - setup
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: '22'

            - name: Restore Cache Dependencies
              uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Vitest Check
              run: yarn test


    build:
        runs-on: ubuntu-latest
        needs:
            - setup
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: '22'

            - name: Restore Cache Dependencies
              uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Build Check
              run: yarn build